meta_product_name: "Concisely"
meta_title: "Concisely - Interviews are stressful, but they don't need to be!"
meta_description: "Interviews are stressful, but they don't need to be! Hire a coach, and get interviewed the right way."
meta_image: "logo.png" # should exist in `app/assets/images/`
